########dev##########################
server:
  port: 8889
  servlet:
    context-path: /producer
spring:
  application:
    name: spring-cloud-producer
eureka:
  client:
    fetch-registry: false
    service-url:
#      \u6CE8\u610F\uFF0C\u6D4F\u89C8\u5668\u8BBF\u95EE\u4E0D\u9700\u8981eureka\uFF0C\u4F46\u914D\u7F6E\u5FC5\u987B\u8981
      defaultZone: http://127.0.0.1:8761/eureka/eureka
#########################
